import nextcord
from nextcord.ext import commands

class List(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.boss_location_mapping = {
            "abyssal sire": ("Bosses", "Abyssal Sire"),
            "alchemical hydra": ("Bosses", "Alchemical Hydra"),
            "hydra": ("Bosses", "Alchemical Hydra"),
            "barrows": ("Bosses", "Barrows Chests"),
            "bryophyta": ("Bosses", "Bryophyta"),
            "callisto": ("Bosses", "Callisto and Artio"),
            "artio": ("Bosses", "Callisto and Artio"),
            "cerberus": ("Bosses", "Cerberus"),
            "chaos elemental": ("Bosses", "Chaos Elemental"),
            "chaos fanatic": ("Bosses", "Chaos Fanatic"),
            "commander zilyana": ("Bosses", "Commander Zilyana"),
            "zilyana": ("Bosses", "Commander Zilyana"),
            "corporeal beast": ("Bosses", "Corporeal Beast"),
            "corp": ("Bosses", "Corporeal Beast"),
            "crazy archaeologist": ("Bosses", "Crazy Archaeologist"),
            "dagannoth kings": ("Bosses", "Dagannoth Kings"),
            "rex": ("Bosses", "Dagannoth Kings"),
            "duke sucellus": ("Bosses", "Duke Sucellus"),
            "duke": ("Bosses", "Duke Sucellus"),
            "general graardor": ("Bosses", "General Graardor"),
            "bandos": ("Bosses", "General Graardor"),
            "giant mole": ("Bosses", "Giant Mole"),
            "mole": ("Bosses", "Giant Mole"),
            "grotesque guardians": ("Bosses", "Grotesque Guardians"),
            "guardians": ("Bosses", "Grotesque Guardians"),
            "hespori": ("Bosses", "Hespori"),
            "kalphite queen": ("Bosses", "Kalphite Queen"),
            "kq": ("Bosses", "Kalphite Queen"),
            "king black dragon": ("Bosses", "King Black Dragon"),
            "kbd": ("Bosses", "King Black Dragon"),
            "kraken": ("Bosses", "Kraken"),
            "kree'arra": ("Bosses", "Kree'arra"),
            "kreearra": ("Bosses", "Kree'arra"),
            "armadyl": ("Bosses", "Kree'arra"),
            "k'ril tsutsaroth": ("Bosses", "K'ril Tsutsaroth"),
            "kril": ("Bosses", "K'ril Tsutsaroth"),
            "zamorak": ("Bosses", "K'ril Tsutsaroth"),
            "nex": ("Bosses", "Nex"),
            "obor": ("Bosses", "Obor"),
            "phantom muspah": ("Bosses", "Phantom Muspah"),
            "muspah": ("Bosses", "Phantom Muspah"),
            "sarachnis": ("Bosses", "Sarachnis"),
            "scorpia": ("Bosses", "Scorpia"),
            "skotizo": ("Bosses", "Skotizo"),
            "tempoross": ("Bosses", "Tempoross"),
            "the fight caves": ("Bosses", "The Fight Caves"),
            "jad": ("Bosses", "The Fight Caves"),
            "the gauntlet": ("Bosses", "The Gauntlet"),
            "gauntlet": ("Bosses", "The Gauntlet"),
            "cg": ("Bosses", "The Gauntlet"),
            "the inferno": ("Bosses", "The Inferno"),
            "inferno": ("Bosses", "The Inferno"),
            "the leviathan": ("Bosses", "The Leviathan"),
            "leviathan": ("Bosses", "The Leviathan"),
            "the nightmare": ("Bosses", "The Nightmare"),
            "nightmare": ("Bosses", "The Nightmare"),
            "thermonuclear smoke devil": ("Bosses", "Thermonuclear Smoke Devil"),
            "smoke devil": ("Bosses", "Thermonuclear Smoke Devil"),
            "the whisperer": ("Bosses", "The Whisperer"),
            "whisperer": ("Bosses", "The Whisperer"),
            "whisp": ("Bosses", "The Whisperer"),
            "vardorvis": ("Bosses", "Vardorvis"),
            "spindel": ("Bosses", "Venenatis and Spindel"),
            "venenatis": ("Bosses", "Venenatis and Spindel"),
            "vet'ion": ("Bosses", "Vet'ion and Calvar'ion"),
            "calvar'ion": ("Bosses", "Vet'ion and Calvar'ion"),
            "vetion": ("Bosses", "Vet'ion and Calvar'ion"),
            "calvarion": ("Bosses", "Vet'ion and Calvar'ion"),
            "vorkath": ("Bosses", "Vorkath"),
            "wintertodt": ("Bosses", "Wintertodt"),
            "wt": ("Bosses", "Wintertodt"),
            "zalcano": ("Bosses", "Zalcano"),
            "zulrah": ("Bosses", "Zulrah"),
            "beginner": ("Clues", "Beginner Treasure Trails"),
            "easy": ("Clues", "Easy Treasure Trails"),
            "medium": ("Clues", "Medium Treasure Trails"),
            "hard": ("Clues", "Hard Treasure Trails"),
            "elite": ("Clues", "Elite Treasure Trails"),
            "master": ("Clues", "Master Treasure Trails"),
            "hard rare": ("Clues", "Hard Treasure Trails (Rare)"),
            "elite rare": ("Clues", "Elite Treasure Trails (Rare)"),
            "master rare": ("Clues", "Master Treasure Trails (Rare)"),
            "barbarian assult": ("Minigames", "Barbarian Assault"),
            "agility arena": ("Minigames", "Brimhaven Agility Arena"),
            "castle wars": ("Minigames", "Castle Wars"),
            "fishing trawler": ("Minigames", "Fishing Trawler"),
            "giants foundry": ("Minigames", "Giants' Foundry"),
            "gnome restaurant": ("Minigames", "Gnome Restaurant"),
            "gotr": ("Minigames", "Guardians of the Rift"),
            "guardians of the rift": ("Minigames", "Guardians of the Rift"),
            "hallowed": ("Minigames", "Hallowed Sepulchre"),
            "hs": ("Minigames", "Hallowed Sepulchre"),
            "hallowed sepulchre": ("Minigames", "Hallowed Sepulchre"),
            "lms": ("Minigames", "Last Man Standing"),
            "last man standing": ("Minigames", "Last Man Standing"),
            "magic training arena": ("Minigames", "Magic Training Arena"),
            "mta": ("Minigames", "Magic Training Arena"),
            "mahogany homes": ("Minigames", "Mahogany Homes"),
            "pest control": ("Minigames", "Pest Control"),
            "rouges den": ("Minigames", "Rogues' Den"),
            "shades fo morton": ("Minigames", "Shades of Mort'ton"),
            "sould wars": ("Minigames", "Soul Wars"),
            "temple trekking": ("Minigames", "Temple Trekking"),
            "tithe farm": ("Minigames", "Tithe Farm"),
            "trouble brewing": ("Minigames", "Trouble Brewing"),
            "volcanic mine": ("Minigames", "Volcanic Mine"),
            "aerial fishing": ("Other", "Aerial Fishing"),
            "pets": ("Other", "All Pets"),
            "camdozaal": ("Other", "Camdozaal"),
            "champions challange": ("Other", "Champion's Challenge"),
            "chaos druids": ("Other", "Chaos Druids"),
            "chompy bird hunting": ("Other", "Chompy Bird Hunting"),
            "creature creation": ("Other", "Creature Creation"),
            "cyclopes": ("Other", "Cyclopes"),
            "forestry": ("Other", "Forestry"),
            "fossil island notes": ("Other", "Fossil Island Notes"),
            "glough": ("Other", "Glough's Experiments"),
            "gloughs experiments": ("Other", "Glough's Experiments"),
            "miscellaneous": ("Other", "Miscellaneous"),
            "misc": ("Other", "Miscellaneous"),
            "monkey backpacks": ("Other", "Monkey Backpacks"),
            "motherload mine": ("Other", "Motherlode Mine"),
            "my notes": ("Other", "My Notes"),
            "random events": ("Other", "Random Events"),
            "random event": ("Other", "Random Events"),
            "reventants": ("Other", "Revenants"),
            "rooftop agility": ("Other", "Rooftop Agility"),
            "agility": ("Other", "Rooftop Agility"),
            "shayzien armour": ("Other", "Shayzien Armour"),
            "shooting stars": ("Other", "Shooting Stars"),
            "pets skilling": ("Other", "Skilling Pets"),
            "skilling pets": ("Other", "Skilling Pets"),
            "slayer": ("Other", "Slayer"),
            "tzhaar": ("Other", "TzHaar"),
            "cox": ("Raids", "Chambers of Xeric"),
            "chambers of xeric": ("Raids", "Chambers of Xeric"),
            "tob": ("Raids", "Theatre of Blood"),
            "theatre of blood": ("Raids", "Theatre of Blood"),
            "toa": ("Raids", "Tombs of Amascut"),
            "tombs of amascut": ("Raids", "Tombs of Amascut")            
        }

    @commands.command()
    async def list(self, ctx, category: str = None):
        if category is None:
            # Display general help message
            response = "**```Användning: !list <kategori>\n"
            response += "Tillgängliga kategorier: all, bosses, raids, Clues, minigames, other```**"
            await ctx.send(response)
            return

        # Handle different categories
        category = category.lower()
        if category == "all":
            # Display all categories and their entries
            await ctx.send("**```Här ska det visas information för alla command```**")
        elif category in ["bosses", "raids", "clues", "minigames", "other"]:
            # Display specific category
            await ctx.send(f"**```Här ska det visas information för alla command i kategorin '{category}'```**")
        else:
            await ctx.send(f"**```'{category}' är inte en giltig kategori, skriv !list för att se alla kategorier```**")

def setup(bot):
    bot.add_cog(List(bot))